Pr
gusdn0108/java-baseball pull request #1
Opened 2023-05-13 07:40 UTC by gusdn0108

2023-05-13 08:38 UTC, green-kong requested changes
코멘트 남겨놨으니까 내용 반영한다음에 푸시한 다음에 말해줘.
아직 기능 구현 안된 부분 있던데 거기까지 마무리해서 푸시할수 있도록

2023-05-13 08:38 UTC, green-kong commented on src/main/java/baseball/Application.java
> +        String numberWrite = Console.readLine();
> 기능 구현을 모두 정상적으로 했더라도 요구 사항에 명시된 출력값 형식을 지키지 않을 경우 0점으로 처리한다.

기본적인 요구사항은 지키자

2023-05-13 08:38 UTC, green-kong commented on src/main/java/baseball/Application.java
> +```
pr 날리기 전엔 주석제거.

2023-05-13 08:38 UTC, green-kong commented on src/main/java/baseball/Application.java
> +}
https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/

2023-05-13 08:38 UTC, green-kong commented on src/main/java/baseball/Application.java
> +            ArrayList<Integer> getNumber = playerNumber();
get이라는 단어는 일반적으로 getter metho의 네이밍으로 쓰이기 때문에 변수명을 설정하는데는 적절하지 않음.

2023-05-13 08:38 UTC, green-kong commented on src/main/java/baseball/Application.java
> +            getNumber.add(Integer.parseInt(number));
숫자로 이뤄진 문자열이 아닌 다른 형식의 문자열("일23", "3사5"...) 사용자가 입력한 경우 어떻게 처리해야될지 생각해봐

2023-05-13 08:38 UTC, green-kong commented on src/main/java/baseball/Application.java
> +    public static void result(Integer ballCount, Integer strikeCount) {
왜 이거 두 method 이름이 같음?  하나는 결과를 계산하는 역할을 하고있고, 하나는 결과를 출력하는 전혀 다른 역할인데 왜 같은 이름으로 method를 오버로드 함?

2023-05-13 08:38 UTC, green-kong commented on src/main/java/baseball/Application.java
> +            getNumber.add(Integer.parseInt(number));
사욪자가 입력한 값이 3자리인지 아닌지 검증하는 로직도 필요하지 않을까?

2023-05-13 08:38 UTC, green-kong commented on src/main/java/baseball/Application.java
> +    public static ArrayList<Integer> playerNumber() {
method 명은 동사로 시작하는게 컨벤션.

2023-05-13 08:38 UTC, green-kong commented on src/main/java/baseball/Application.java
> +        return new ArrayList<>(Arrays.asList(ballCount, strikeCount));
리스트에 담아서 값을 반환하는 방식이 적절할까?
스스로 짠 코드는 0번 인덱스에는 ballCount, 1번 인덱스에는 strikeCount가 들어있다는걸 쉽게 인지할 수 있지만,
다른 사람이 보기에는 애매할 것 같은데, List말고 **다른 컬렉션**을 이용해서 다른사람들도 좀 더 쉽게 이해할수 있는 코드를 만들수 있을 것 같아.

2023-05-13 08:38 UTC, green-kong commented on docs/README.md
> +   - 2을 누르면 `게임이 종료되었습니다` 라는 문구열 생성 [ ]
아직 구현 안된것 같은데, 이번 리뷰 반영하면서 여기까지 구현해봐.

2023-05-13 08:38 UTC, green-kong commented on docs/README.md
> +  -  잘못된 값을 입력할 경우 `IllegalArgumentException`을 발생시키고 애플리케이션이 종료되어야 한다.
이것도 리뷰 반영하면서 구현.

2023-05-13 08:38 UTC, green-kong commented on docs/README.md
> + 어떤건지 정확하게 모르겠음..
아직 몰라도 됨

2023-05-13 08:44 UTC, green-kong requested changes

2023-05-13 08:44 UTC, green-kong commented on src/main/java/baseball/Application.java
> +}
![image](https://github.com/gusdn0108/java-baseball/assets/96301958/267ddf8b-dc58-486a-a5fd-a348f85e015e)

https://seongwon.dev/Git/20220303-%ED%8C%8C%EC%9D%BC%EC%9D%98_%EB%A7%88%EC%A7%80%EB%A7%89_%EA%B0%9C%ED%96%89/

파일의 마지막 줄엔 항상 개행으로

2023-05-13 08:44 UTC, green-kong commented on src/main/java/baseball/Application.java
> +```
pr 날리기 전엔 주석제거.

2023-05-15 15:15 UTC, merged

2023-05-15 15:53 UTC, gusdn0108 commented on src/main/java/baseball/Application.java
> +    public static ArrayList<Integer> playerNumber() {
이 컨벤션이라는게 무슨뜻인지 잘모르겠어요..

2023-05-15 15:55 UTC, gusdn0108 commented on src/main/java/baseball/Application.java
> +        return new ArrayList<>(Arrays.asList(ballCount, strikeCount));
컬렉션은 말씀드렸던것처럼 이 부분을 어떻게 리팩토링할지 다시 한번 보고 생각해보겠습니다...

2023-05-15 16:00 UTC, gusdn0108 commented on src/main/java/baseball/Application.java
> +            ArrayList<Integer> getNumber = playerNumber();
죄송합니다 .. 배웟는데 까먹었어요 다시 공부할게요 ..